### ISSUE TITLE
Tips&tricks: skip tests in order to compile

### ISSUE THREAD

**Issue by liar666** [pwojnowski/jdee-server#1]
Hi,

I'm running PC-BSD (I know... I know...), when compiling with 
mvn assembly:assembly
commandline just frooze on the first test.

Since I'm used to this kind of problems with other projects, I succeeded compiling the jar with:
mvn -Dmaven.test.skip=true -DskipTests=true assembly:assembly

In case this can help someone else...

**Comment by pwojnowski** [comment]
One test hangs sometimes, but most probably we won't correct it, because most probably we'll switch to a new backed.

BTW do not use this repo, but jdee/jdee-server instead.

Anyway, I've changed the build command to skip tests. Thanks! :+1:
